apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: withoutdb
spec:
  selector:
    matchLabels:
      app: withoutdb
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: withoutdb
    spec:
      containers:
        - name: withoutdb
          image: pritiswami123/withoutdatabase # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: withoutdb-k8ssvc
spec:
  selector:
    app: withoutdb
  ports:
    - protocol: "TCP"
      port: 9292 # The port that the service is running on in the cluster
      targetPort: 9292 # The port exposed by the service
  type: NodePort # type of the service.